INSERT INTO editoras (id, nome) VALUES (1, 'Jorge Zahar Editor');
INSERT INTO editoras (id, nome) VALUES (2, 'Novo Conceito');
INSERT INTO editoras (id, nome) VALUES (3, 'Nova Fronteira');
INSERT INTO editoras (id, nome) VALUES (4, 'Sextante');
INSERT INTO editoras (id, nome) VALUES (5, 'Oxford');
INSERT INTO editoras (id, nome) VALUES (6, 'Agir');
INSERT INTO editoras (id, nome) VALUES (7, 'Bertrand Brasil');
INSERT INTO editoras (id, nome) VALUES (8, 'Incaer');
INSERT INTO editoras (id, nome) VALUES (9, 'Record');
INSERT INTO editoras (id, nome) VALUES (10, 'PubliFolha');
INSERT INTO editoras (id, nome) VALUES (11, 'Lonely planet');
INSERT INTO editoras (id, nome) VALUES (12, 'Pearson Prentice Hall');
INSERT INTO editoras (id, nome) VALUES (13, 'Campus Concursos');
INSERT INTO editoras (id, nome) VALUES (14, 'Nobel');
INSERT INTO editoras (id, nome) VALUES (15, 'Objetiva');
INSERT INTO editoras (id, nome) VALUES (16, 'Ciranda Cultural');
INSERT INTO editoras (id, nome) VALUES (17, 'Melhoramentos');
INSERT INTO editoras (id, nome) VALUES (18, 'Campus');
INSERT INTO editoras (id, nome) VALUES (19, 'Brasport');
INSERT INTO editoras (id, nome) VALUES (20, 'Madras');
INSERT INTO editoras (id, nome) VALUES (21, 'Editora 34');
INSERT INTO editoras (id, nome) VALUES (22, 'Alegro');
INSERT INTO editoras (id, nome) VALUES (23, 'Imago');
INSERT INTO editoras (id, nome) VALUES (24, 'Abril');
INSERT INTO editoras (id, nome) VALUES (25, 'Hueber');
INSERT INTO editoras (id, nome) VALUES (26, 'JORGE ZAHAR EDITOR');
INSERT INTO editoras (id, nome) VALUES (27, 'FTD');
INSERT INTO editoras (id, nome) VALUES (28, 'Cambridge University Press');
INSERT INTO editoras (id, nome) VALUES (29, 'Penguin Popular Classics');
INSERT INTO editoras (id, nome) VALUES (30, 'Ballantine Books');
INSERT INTO editoras (id, nome) VALUES (31, 'Casa Publicadora Brasileira');
INSERT INTO editoras (id, nome) VALUES (32, 'RiMa');
INSERT INTO editoras (id, nome) VALUES (33, 'Ática');
INSERT INTO editoras (id, nome) VALUES (34, 'Bestbolso');
INSERT INTO editoras (id, nome) VALUES (35, 'Wizard Brasil Franchising');
INSERT INTO editoras (id, nome) VALUES (36, 'Hal-Leonard');
INSERT INTO editoras (id, nome) VALUES (37, 'LTC');
INSERT INTO editoras (id, nome) VALUES (38, 'Bookman');
INSERT INTO editoras (id, nome) VALUES (39, 'McGrawHill');
INSERT INTO editoras (id, nome) VALUES (40, 'Makron Books');
INSERT INTO editoras (id, nome) VALUES (41, 'Abril Coleções');
INSERT INTO editoras (id, nome) VALUES (42, 'Ponto de Leitura');
INSERT INTO editoras (id, nome) VALUES (43, 'Leitura');
INSERT INTO editoras (id, nome) VALUES (44, 'JARDIM DOS LIVROS');
INSERT INTO editoras (id, nome) VALUES (45, 'RECORD');
INSERT INTO editoras (id, nome) VALUES (46, '8INVERSO');
INSERT INTO editoras (id, nome) VALUES (47, 'LAROUSSE DO BRASIL');
INSERT INTO editoras (id, nome) VALUES (48, 'UNIVERSO DOS LIVROS');
INSERT INTO editoras (id, nome) VALUES (49, 'Geração Editorial');
INSERT INTO editoras (id, nome) VALUES (50, 'Planeta do Brasil');
INSERT INTO editoras (id, nome) VALUES (51, 'Editora Vozes');
INSERT INTO editoras (id, nome) VALUES (52, 'Fontanar');
INSERT INTO editoras (id, nome) VALUES (53, 'Saraiva');
INSERT INTO editoras (id, nome) VALUES (54, 'Mundo Cristão');
INSERT INTO editoras (id, nome) VALUES (55, 'Intríseca');
INSERT INTO editoras (id, nome) VALUES (56, 'Catalonia');
INSERT INTO editoras (id, nome) VALUES (57, 'Central Gospel');
INSERT INTO editoras (id, nome) VALUES (58, 'Galas Ediciones');
INSERT INTO editoras (id, nome) VALUES (59, 'Comunicação eficaz produções');
INSERT INTO editoras (id, nome) VALUES (60, 'Sociedade Bíblica do Brasil');
INSERT INTO editoras (id, nome) VALUES (61, 'Graça Editora');
INSERT INTO editoras (id, nome) VALUES (62, 'Thomas Nelson Brasil');
INSERT INTO editoras (id, nome) VALUES (63, 'Novo Século');
INSERT INTO editoras (id, nome) VALUES (64, 'Editora Verdade Viva');
INSERT INTO editoras (id, nome) VALUES (65, 'Ministério Verdade Viva');
INSERT INTO editoras (id, nome) VALUES (66, 'Willem Books');
INSERT INTO editoras (id, nome) VALUES (67, 'Novatec');
INSERT INTO editoras (id, nome) VALUES (68, 'Editora Kactus');
INSERT INTO editoras (id, nome) VALUES (69, 'CLA Editora');
INSERT INTO editoras (id, nome) VALUES (70, 'Suma de Letras');
INSERT INTO editoras (id, nome) VALUES (71, 'Gente Editora');
INSERT INTO editoras (id, nome) VALUES (72, 'Arqueiro');
INSERT INTO editoras (id, nome) VALUES (73, 'Editora Basileia ');
INSERT INTO editoras (id, nome) VALUES (74, 'Editora Central Gospel');
INSERT INTO editoras (id, nome) VALUES (75, 'Editora Basileia');
INSERT INTO editoras (id, nome) VALUES (76, 'Livro Rápido');
INSERT INTO editoras (id, nome) VALUES (77, 'Premius Editora');
INSERT INTO editoras (id, nome) VALUES (78, 'Editora Escala');
INSERT INTO editoras (id, nome) VALUES (79, 'Belotur');
INSERT INTO editoras (id, nome) VALUES (80, 'Editora Abril');
INSERT INTO editoras (id, nome) VALUES (81, 'Sociedade Bíblica Brasileira');
INSERT INTO editoras (id, nome) VALUES (82, 'IBEP');
INSERT INTO editoras (id, nome) VALUES (83, 'Longman');
INSERT INTO editoras (id, nome) VALUES (84, 'MC');
INSERT INTO editoras (id, nome) VALUES (85, 'Vida Acadêmica');
INSERT INTO editoras (id, nome) VALUES (86, 'Fiel Editora');
INSERT INTO editoras (id, nome) VALUES (87, 'Editora Aleph');
INSERT INTO editoras (id, nome) VALUES (88, 'Editora Universidade UFPE');
INSERT INTO editoras (id, nome) VALUES (89, 'Orvalho.com');
INSERT INTO editoras (id, nome) VALUES (90, 'Bello  Publicações');
INSERT INTO editoras (id, nome) VALUES (91, 'Graça Editorial');
INSERT INTO editoras (id, nome) VALUES (92, 'Adhonep');
INSERT INTO editoras (id, nome) VALUES (93, 'Massangana');
INSERT INTO editoras (id, nome) VALUES (94, 'Companhia das Letras');
INSERT INTO editoras (id, nome) VALUES (95, 'JCS Editora');
INSERT INTO editoras (id, nome) VALUES (96, 'Ministério Jimmy Swaggart');
INSERT INTO editoras (id, nome) VALUES (97, 'Rhema Brasil');
INSERT INTO editoras (id, nome) VALUES (98, 'Babecco');
INSERT INTO editoras (id, nome) VALUES (99, 'Julián Melgosa e Michelson Borges');
INSERT INTO editoras (id, nome) VALUES (100, 'Coleção Legado Bud Wright');
INSERT INTO editoras (id, nome) VALUES (101, 'Willën books');
INSERT INTO editoras (id, nome) VALUES (102, 'Getsêmani');
INSERT INTO editoras (id, nome) VALUES (103, 'Disney Pixar');
INSERT INTO editoras (id, nome) VALUES (104, 'CCS Gráfica e Editora');
INSERT INTO editoras (id, nome) VALUES (105, 'Coleção EI');
INSERT INTO editoras (id, nome) VALUES (106, 'Rhema Brasil Publicações');
INSERT INTO editoras (id, nome) VALUES (107, 'Wizard');
INSERT INTO editoras (id, nome) VALUES (108, 'Mensagem para Todos');
INSERT INTO editoras (id, nome) VALUES (109, 'Ediouro');
INSERT INTO editoras (id, nome) VALUES (110, 'Rhema Brasil publicações');
INSERT INTO editoras (id, nome) VALUES (111, 'Frutos do Espírito');
INSERT INTO editoras (id, nome) VALUES (112, 'Editora Betânia');
INSERT INTO editoras (id, nome) VALUES (113, 'Editora Vida');
INSERT INTO editoras (id, nome) VALUES (114, 'Academia');
INSERT INTO editoras (id, nome) VALUES (115, 'United Press');
INSERT INTO editoras (id, nome) VALUES (116, 'Paulinas');
INSERT INTO editoras (id, nome) VALUES (117, 'Culturama');
INSERT INTO editoras (id, nome) VALUES (118, 'bvbooks');
INSERT INTO editoras (id, nome) VALUES (119, 'Luz e Vida');
INSERT INTO editoras (id, nome) VALUES (120, 'Lynne Hammond/Patsy Cameneti');
INSERT INTO editoras (id, nome) VALUES (121, 'Otávio Lino/Marcio Sanches');
INSERT INTO editoras (id, nome) VALUES (122, 'Geográfica Editora');
INSERT INTO editoras (id, nome) VALUES (123, 'Cristiano Arcoverde Comunicações e Treinamentos');
INSERT INTO editoras (id, nome) VALUES (124, 'Vida');
INSERT INTO editoras (id, nome) VALUES (125, 'Bello Publicações');
INSERT INTO editoras (id, nome) VALUES (126, 'Editoria Betânia');
INSERT INTO editoras (id, nome) VALUES (127, 'Cristiano Arcoverde Comunicação e Treinamentos');
INSERT INTO editoras (id, nome) VALUES (128, 'Editora Árvore da Vida');
INSERT INTO editoras (id, nome) VALUES (129, 'Chara');
INSERT INTO editoras (id, nome) VALUES (130, 'Hagnos');
INSERT INTO editoras (id, nome) VALUES (131, 'Alethos Editorial');
