INSERT INTO autores (id, nome, nacionalidade) VALUES (1, 'John Lukacs', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (2, 'David Leavitt', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (3, 'Antoine Vitkine', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (4, 'William C. Taylor e Polly LaBarre', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (5, 'F. H. Hinsley & Alan Stripp', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (6, 'Stuart Ball', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (7, 'Leander Kahney', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (8, 'Abel Basti', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (9, 'Stephen E. Ambrose', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (10, 'Rui Moreira Lima', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (11, 'Simon Singh', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (12, 'Sylvia Goulding', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (13, 'Jim Selman', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (14, 'William Douglas', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (15, 'Henrique Rattner', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (16, 'Luiz Eduardo Soares, André Batista, Rodrigo Pimentel', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (17, 'Luiz Eduardo Soares, Cláudio Ferraz, André Batista, Rodrigo Pimentel', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (18, 'Alfred J. Keller', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (19, 'Fábio Braga de Alencar', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (20, 'Grady Booch, James Rumbaugh, Ivar Jacobson', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (21, 'Andrew S. Tanenbaum', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (22, 'Alfred Lansing', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (23, 'Aguinaldo Aragon Fernandes, Vladimir Ferraz de Abreu', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (24, 'Fabrício Mariano', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (25, 'Aurélio Buarque de Holanda Ferreira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (26, 'Jesús Hernández', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (27, 'Sun Tzu', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (28, 'Diana Preston', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (29, 'Robert Falcon Scott', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (30, 'Bryan Mark Rigg', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (31, 'Max Hueber Verlag', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (32, 'Paul Strathern', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (33, 'Adriano da Gama Cury', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (34, 'Ana Bremon', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (35, 'H. Rider Haggard', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (36, 'Robert Harris', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (37, 'T. Harv Eker', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (38, 'James C. Hunter', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (39, 'Mark Finley', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (40, 'Nilson da Silva', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (41, 'Nelson Piletti', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (42, 'Elmasri & Navathe', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (43, 'H. M. Deitel & P. J. Deitel', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (44, 'Roger S. Pressman', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (45, 'Silberschatz – Galvin – Gagne', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (46, 'J. Glenn Brookshear', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (47, 'Herbert Schildt', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (48, 'Bernardinho', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (49, 'Ricardo Soares & William Douglas', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (50, 'Kim Heldman', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (51, 'Douglas E. Comer', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (52, 'Nando Parrado, Vince Rause', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (53, 'Stephen King', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (54, 'Cláudio Bojunga', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (55, 'Luís Augusto Símon e Marcelo Prado', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (56, 'C. G. SWEETING ', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (57, 'TEC, NECHAMA', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (58, 'RASHKE, RICHARD', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (59, 'LAROUSSE EDITORIAL', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (60, 'ALBERTO DELLISOLA', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (61, 'Fernando Jorge', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (62, 'Padre Fábio de Melo', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (63, 'Graciliano Ramos', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (64, 'Olivier Ninge & Simonne Mortera', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (65, 'Ana Beatriz Barbosa Silva', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (66, 'Nilson Teixeira de Almeida', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (67, 'Carlos Saldanha Maranhão', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (68, 'Stormie Omartian', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (69, 'Antonio Mendez & Matt Baglio', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (70, 'Armando de Ramón', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (71, 'Ruth & Elmer Towns', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (72, 'Cristiano Arcoverde', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (73, 'Ellen G. White', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (74, 'Abe Huber', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (75, 'Kenneth E. Hagin', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (76, 'Charles Sheldon', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (77, 'Sheila Walsh', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (78, 'Nonna Bannister', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (79, 'Bernard W. Snelgrove', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (80, 'Dave Roberson', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (81, 'Kenneth E. Hagin e Kenneth Hagin Jr.', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (82, 'Alejandro Bullón', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (83, 'Walter Nather Jr.', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (84, 'Ricardo R. Lecheta', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (85, 'Mary Kay Ash', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (86, 'Carlos Ruiz Zafón', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (87, 'Nigel Cawthorne', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (88, 'Ignácio de Loyola Brandão', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (89, 'William P. Young', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (90, 'Lúcio Barreto Jr', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (91, 'Davi Lago e Lúcio Barreto Jr', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (92, 'Perilo Borba', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (93, 'Lúcio Barreto Jr & Davi Lago', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (94, 'Arilton Oliveira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (95, 'Sandra Santos', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (96, 'Max Lucado', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (97, 'Loron Wade', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (98, 'Elvis Oliveira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (99, 'Lúcio Barreto Jr & Richarde Guerra', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (100, 'Charles M. Sheldon', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (101, 'Eça de Queirós', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (102, 'Victoria Keller', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (103, 'Elias Freire', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (104, 'Alceu Luiz Pazzinato & Maria Helena Valente Senise', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (105, 'Richard Acklam with Sally Burgess', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (106, 'Billy Graham', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (107, 'Jesse Lyman Hurlbut', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (108, 'Benny Hinn', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (109, 'Sarah Young', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (110, 'Liao Yiwu', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (111, 'Miroslav Volf', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (112, 'Rice Broocks', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (113, 'Franklin Ferreira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (114, 'Paulo Vieira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (115, 'Anthony Burgess', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (116, 'Nilton Pereira da Cunha', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (117, 'Augusto Cury', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (118, 'Janio Cesar', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (119, 'Joyce Meyer', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (120, 'Frederico Pernambuco de Mello', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (121, 'Julie Orringer', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (122, 'Jimmy Swaggart', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (123, 'Tony Cooke', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (124, 'Fernandes Oliveira', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (125, 'Fernando Morais', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (126, 'Assuero Seixas', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (127, 'Josué Gonçalves', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (128, 'Jorge Linhares', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (129, 'Bud Wright', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (130, 'Jedida Ferro', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (131, 'Rick Renner', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (132, 'E. W. Kenyon', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (133, 'T. L. Osborn', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (134, 'Charles Capps', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (135, 'Mark W. Baker', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (136, 'Silas Malafaia', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (137, 'Walter Nather Jr', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (138, 'Sherry Argov', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (139, 'Laurentino Gomes', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (140, 'Eduardo Bueno', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (141, 'Daniel Souza', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (142, 'Kenneth W. Hagin', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (143, 'Simon Potter', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (144, 'Mark hankins', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (145, 'Myrna Grant', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (146, 'C.S. Lewis', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (147, 'Nancy Dufresne', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (148, 'Rick Warren', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (149, 'Mark Hankins', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (150, 'Elizabeth George', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (151, 'Dag Tessore', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (152, 'David Emigh', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (153, 'Luís Gonçalves/Diogo Cavalcanti', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (154, 'Abraão de Almeida', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (155, 'Alexandre Lopes', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (156, 'Dr. Ismael Sobrinho', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (157, 'Tim LaHaye', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (158, 'Luciano & Kelly Subirá', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (159, 'David Murray', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (160, 'Irmão Yun com Paul Hattaway', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (161, 'Shona & David Murray', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (162, 'Corrie Ten Boom com Elizabeth e John Sherril', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (163, 'Kenneth Hagin Jr', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (164, 'Godofredo Couto', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (165, 'André Martins', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (166, 'Alex Moriá', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (167, 'Dong Yu Lan', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (168, 'Pedro Dong', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (169, 'Mosab Hassan Yousef', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (170, 'Dra. Caroline Leaf', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (171, 'Hernandes Dias Lopes', NULL);
INSERT INTO autores (id, nome, nacionalidade) VALUES (172, 'Jason Diamantino', NULL);
